In [ ]:
**Задание на повторение материала

#### 1. 
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 
невключительно

In [4]:
import numpy as np

In [8]:
a= np.linspace(12, 23, 12)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

#### 2. 
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [89]:
b = np. resize(a, (2, 6))
b

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [90]:
b1 = np. resize(a, (12, 1))
b1

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

In [91]:
b2 = np. resize(a, (6, 2))
b2

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [92]:
b3 = np. resize(a, (3, 4))
b3

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [93]:
b4 = np. resize(a, (4, 3))
b4

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

#### 3. 
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 
(в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [85]:
c = a.reshape (12, -1)
c

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

In [71]:
c1 = a.reshape(6, -1)
c1

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [75]:
c2 = a.reshape(4, -1)
c2

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [82]:
c3 = a.reshape (-1, 4)
c3

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [84]:
c4 = a.reshape (-1, 2)
c4

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

#### 4.
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

ответ: нет

#### 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального 
распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [101]:
a = np.random.randn(3, 4)
a

[[ 0.03777261 -0.13544849 -0.01002595  1.67080819]
 [-0.66437971 -0.60555494 -0.65099088  0.51256776]
 [ 0.26238882 -0.58273165  1.36842193  0.05336866]]


In [102]:
a.mean()

0.10468302930336866

In [103]:
np.std(a)

0.7336230880624351

In [110]:
b = a.flatten()
b

array([ 0.03777261, -0.13544849, -0.01002595,  1.67080819, -0.66437971,
       -0.60555494, -0.65099088,  0.51256776,  0.26238882, -0.58273165,
        1.36842193,  0.05336866])

#### 6. 
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [94]:
a = np.arange(20,0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно 
с интервалом 2. В чем разница между массивами a и b?

In [96]:
b = np.arange (20,1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

В чем разница между массивами a и b?
ответ: между массивами нет разницы

#### 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [119]:
a=np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [120]:
b=np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [121]:
v = np.vstack([a, b])
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [122]:
v.size

10

#### 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая 
из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. 
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? 
Получится ли вычислить обратную матрицу для матрицы B и почему?

In [9]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
A = a.reshape (3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
At = A.T
At

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [66]:
B = A@At
B

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [22]:
B.shape

(3, 3)

In [23]:
#для матрицы B можно найти обратную матрицу, т.к. она квадратная

#### 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [48]:
import numpy.random

In [51]:
np.random.seed(10)
print(np.random.random())

0.771320643266746


#### 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых 
чисел от 0 до 16 невключительно. 

In [54]:
c = np.linspace(0, 15, 16)
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

#### 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B 
из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [71]:
C = np.resize (c, (3,3))
C

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [72]:
D = C*10 + B
D

array([[ 14.,  48.,  82.],
       [ 68., 166., 264.],
       [122., 284., 446.]])

In [98]:
det = np.linalg.det(D)
rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)

print(f"определитель = {det}" '\n'
      f"ранг = {rank}" '\n'
      "обратная матрица:" '\n'
      f"{D_inv})")

определитель = 7.678229636797736e-12
ранг = 2
обратная матрица:
[[-1.22424054e+14  2.44848108e+14 -1.22424054e+14]
 [ 2.44848108e+14 -4.89696216e+14  2.44848108e+14]
 [-1.22424054e+14  2.44848108e+14 -1.22424054e+14]])


In [ ]:
#### 13 - не осислила
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу 
D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему 
элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть 
равны соответствующему элементу матрицы C.